/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as FacilitatiRouteImport } from './routes/facilitati'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as TermeniSiConditiiRouteImport } from './routes/termeni-si-conditii'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatiRoute = FacilitatiRouteImport.update({
  id: '/facilitati',
  path: '/facilitati',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniSiConditiiRoute = TermeniSiConditiiRouteImport.update({
  id: '/termeni-si-conditii',
  path: '/termeni-si-conditii',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/facilitati': typeof FacilitatiRoute
  '/galerie': typeof GalerieRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/facilitati': typeof FacilitatiRoute
  '/galerie': typeof GalerieRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/facilitati': typeof FacilitatiRoute
  '/galerie': typeof GalerieRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/despre'
    | '/facilitati'
    | '/galerie'
    | '/termeni-si-conditii'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/despre'
    | '/facilitati'
    | '/galerie'
    | '/termeni-si-conditii'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/despre'
    | '/facilitati'
    | '/galerie'
    | '/termeni-si-conditii'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  FacilitatiRoute: typeof FacilitatiRoute
  GalerieRoute: typeof GalerieRoute
  TermeniSiConditiiRoute: typeof TermeniSiConditiiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitati': {
      id: '/facilitati'
      path: '/facilitati'
      fullPath: '/facilitati'
      preLoaderRoute: typeof FacilitatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni-si-conditii': {
      id: '/termeni-si-conditii'
      path: '/termeni-si-conditii'
      fullPath: '/termeni-si-conditii'
      preLoaderRoute: typeof TermeniSiConditiiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  FacilitatiRoute: FacilitatiRoute,
  GalerieRoute: GalerieRoute,
  TermeniSiConditiiRoute: TermeniSiConditiiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
